name: C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    defaults:
      run:
        shell: bash

    env:
      CC: ${{ matrix.c }}
      CXX: ${{ matrix.cxx }}
      BUILD_TYPE: 'Debug'
      EXECUTABLE_NAME: "oop"
      INPUT_FILENAME: "tastatura.txt"
      BUILD_DIR: "build"

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            c: clang-18
            cxx: clang++-18
            name: Ubuntu-Clang

          - os: ubuntu-24.04
            c: gcc-13
            cxx: g++-13
            name: Ubuntu-GCC

          - os: windows-2022
            c: cl
            cxx: cl
            name: Windows-MSVC

          - os: windows-2022
            c: gcc
            cxx: g++
            name: Windows-MinGW
            is_mingw: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare env
        run: |
          mkdir -p artifacts
          if [ ! -f "${INPUT_FILENAME}" ]; then touch "${INPUT_FILENAME}"; fi

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build valgrind cppcheck jq libsfml-dev xvfb

      - name: Install Windows SFML MSVC
        if: matrix.os == 'windows-2022' && !matrix.is_mingw
        run: |
          vcpkg install sfml:x64-windows

      - name: Install Windows SFML MinGW
        if: matrix.is_mingw
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-sfml

      - name: Build MinGW
        if: matrix.is_mingw
        shell: msys2 {0}
        run: |
          cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=./artifacts
          cmake --build build --config Debug -j 2
          cmake --install build --config Debug

      - name: Build Standard
        if: "!matrix.is_mingw"
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=./artifacts
          cmake --build build --config Debug -j 2
          cmake --install build --config Debug

      - name: Memory Check Valgrind
        if: runner.os == 'Linux' && startsWith(matrix.cxx, 'g++')
        run: |
          xvfb-run --auto-servernum valgrind --leak-check=full --error-exitcode=1 ./build/oop < "${INPUT_FILENAME}"

      - name: Memory Check ASan
        if: runner.os == 'Linux' && startsWith(matrix.cxx, 'clang++')
        run: |
          xvfb-run --auto-servernum ./build/oop < "${INPUT_FILENAME}"

      - name: Static Analysis
        if: runner.os == 'Linux'
        run: |
          cppcheck --enable=all --project=build/compile_commands.json --suppress=missingIncludeSystem --error-exitcode=1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: artifacts/
